name: Release

on:
  push:
    tags:
      - v*

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Windows:
    name: Windows
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn bootstrap
      - run: yarn release

  Mac:
    name: Mac
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn bootstrap
      - run: yarn release

  Linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn bootstrap
      - run: yarn release
